<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root [<!ELEMENT root ANY><!ELEMENT item ANY><!ATTLIST item ID ID #REQUIRED><!ATTLIST item Explanation CDATA #IMPLIED>]><root>
<item ID="APPPATH">C:/Users/Administrator/git/access-control-php</item>
<item ID="IL8N">zh-CN</item>
<item ID="DB_TYPE">mysql</item>
<item ID="DB_HOST">localhost:3306</item>
<item ID="DB_NAME">xx3</item>
<item ID="DB_USERNAME">root</item>
<item ID="DB_PASSWORD"></item>
<item ID="DB_CHARSET">UTF-8</item>
<item ID="DB_URL" Explanation="only in java need this"><![CDATA[jdbc:sqlite://localhost:3306/myapp?user=root&password=null]]></item>
<item ID="REGISTERED_GROUP">3311-79-01-01</item>
<item ID="MODE">independent</item>
<item ID="GIS_GUEST_CENTER" Explanation="if guest open the map , the default center">28.466579,119.922241â€Ž</item>
<item ID="ZONE" Explanation="see GB2260 , China-Standard">330281</item>
<item ID="ZONE4">3302</item>
<item ID="ZONE6">330281</item>
<item ID="ZONE8">33028101</item>
<item ID="reLoad">donothing</item>
</root>
